name: lec_app

services:
  price-predict:
    image: estate_model:2
    build: ./ml_service/
    ports:
      - "8001:8000"
    volumes:
      - ./models:/models


  requests:
    image: request_service:1
    build: ./requests/
    deploy: 
      replicas: 1
      restart_policy:
        condition: always
        delay: 5s