channels:
- conda-forge
dependencies:
- python=3.9.6
- pip<=21.2.4
- pip:
  - matplotlib==3.9.2
  - numpy==1.26.4
  - pandas==2.2.3
  - seaborn==0.13.2
  - bokeh==3.6.0
  - pickle4==0.0.1
  - mlflow==2.16.0
  - scikit-learn==1.5.2
  - mlxtend==0.23.2
  - optuna==4.1.0
name: mlflow-env
